# Generated by Django 4.0.3 on 2022-03-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
