# Generated by Django 4.0.3 on 2022-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0004_remove_personal_skills_personal_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
