# Generated by Django 4.0.3 on 2022-03-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0005_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
