# Generated by Django 4.0.3 on 2022-03-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0006_rename_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='personal'),
        ),
    ]
