# Generated by Django 4.0.3 on 2022-03-12 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0012_alter_blog_desc_alter_service_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
