# Generated by Django 4.0.3 on 2022-03-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0014_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comm',
            new_name='comment',
        ),
    ]
