# Generated by Django 4.0.3 on 2022-03-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0016_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='default__images/user.png', null=True, upload_to='products'),
        ),
    ]
