# Generated by Django 4.0.3 on 2022-03-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0023_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
