# Generated by Django 4.0.3 on 2022-03-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourblog', '0024_cat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
